apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv

spec:
  capacity:
    storage: 500Gi
accessModes:
    - ReadWriteMany
persistentVolumeReclaimPolicy: Retain
  nfs:
     path: /home/anicca/tensorrt-triton-yolov5/triton-deploy/models
     server: 20.64.114.103
     readOnly: false
