apiVersion: apps/v1
kind: Deployment
metadata:
  name: bert-qa
  labels:
    app: triton-server
spec:
  selector:
    matchLabels:
      app: triton-server
  replicas: 1
  template:
    metadata:
      labels:
        app: triton-server
    spec:
      volumes:
      - name: model-repo
        persistentVolumeClaim:
          claimName: cv-model
      containers:
      - name: serving
        image: nvcr.io/nvidia/tritonserver:20.12-py3
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "0"
        - name: CUDA_MPS_PIPE_DIRECTORY
          value: "/run/nvidia/nvidia-mps"
        volumeMounts:
        - mountPath: /run/nvidia
          mountPropagation: HostToContainer
          name: nvidia-mps-path
        ports:
        - name: grpc
          containerPort: 8001
        - name: http
          containerPort: 8000
        - name: metrics
          containerPort: 8002
        volumeMounts:
        - name: model-repo
          mountPath: "/models"
        command: ["/bin/sh", "-c"]
        args: ["cd /models /opt/tritonserver/bin/tritonserver --model-repository=/models --allow-gpu-metrics=false --strict-model-config=false"]
      volumes:
      - name: model-repo
        persistentVolumeClaim:
          claimName: cv-model
      - hostPath:
        path: /run/nvidia
        type: ""
      name: nvidia-mps-path
