apiVersion: apps/v1
kind: Deployment
metadata:
  name: bert-qa
  labels:
    app: triton-server
spec:
  selector:
    matchLabels:
      app: triton-server
  replicas: 1
  template:
    metadata:
      labels:
        app: triton-server
    spec:
      volumes:
      - name: model-repo
        persistentVolumeClaim:
          claimName: cv-model
      containers:
      - name: serving
        image: nvcr.io/nvidia/tritonserver:20:03-py3
        ports:
        - name: grpc
          containerPort: 8001
        - name: http
          containerPort: 8000
        - name: metrics
          containerPort: 8002
        volumeMounts:
        - name: model-repo
          mountPath: "/models"
        command: ["/bin/sh", "-c"]
        args: ["cd /models /opt/tritonserver/bin/tritonserver --model-repository=/models --allow-gpu-metrics=false --strict-model-config=false"]
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: model-repo
        persistentVolumeClaim:
          claimName: cv-model
